apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod-release-internal-tls-planner-api-gateway

patches:
  - path: orchestrator.patch.yaml
  - path: api-gateway-ingress-allow.patch.yaml
    target:
      kind: NetworkPolicy
      name: api-gateway-ingress-allow
  - path: orchestrator-egress-internal.patch.yaml
    target:
      kind: NetworkPolicy
      name: orchestrator-egress-internal
