apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis-prod

resources:
  - ../prod-release-internal-tls-planner-service-voice-gateway
  - smart-home-ingress-from-voice-gateway.yaml

patches:
  - path: voice-gateway.patch.yaml
  - path: voice-gateway-egress-smart-home.patch.yaml
    target:
      kind: NetworkPolicy
      name: voice-gateway-egress-orchestrator
