apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smart-home-ingress-from-voice-gateway
spec:
  podSelector:
    matchLabels:
      app: smart-home-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: voice-gateway
      ports:
        - protocol: TCP
          port: 8086
