apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis-prod

resources:
  - ../prod-release-internal-tls-api-gateway-voice-gateway

patches:
  - path: voice-gateway.patch.yaml
