apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis-prod

resources:
  - ../prod-release-internal-tls-voice-gateway-smart-home-service
  - smart-home-ingress-from-orchestrator.yaml

patches:
  - path: orchestrator.patch.yaml
  - path: orchestrator-egress-smart-home.patch.yaml
    target:
      kind: NetworkPolicy
      name: orchestrator-egress-internal
