apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis
resources:
  - ../prod-release-internal-tls-api-gateway-analytics-service

patches:
  - path: api-gateway.patch.yaml
  - path: pc-control.patch.yaml
