package org.jarvis.desktop.service

import javafx.application.Platform
import kotlinx.serialization.json.*
import okhttp3.*
import okio.ByteString.Companion.toByteString
import org.jarvis.desktop.auth.TokenManager
import org.jarvis.desktop.config.AppConfig
import org.slf4j.LoggerFactory
import java.util.concurrent.TimeUnit

/**
 * WebSocket client for voice streaming and receiving transcripts/responses.
 * 
 * This client handles:
 * - Sending audio chunks to the server
 * - Receiving partial and final transcripts
 * - Receiving action responses and TTS audio
 * - Auto-reconnect on connection failures
 * 
 * The isSendingAllowed flag is controlled by VoiceSession to ensure
 * audio is only sent during the LISTENING state.
 */
class VoiceWebSocketClient(
    private val url: String = AppConfig.voiceWebSocketUrl,
    private val onStateChange: (String) -> Unit,
    private val onTranscript: (String, Boolean, String?) -> Unit, // text, isFinal, correlationId
    private val onResponse: (String, String?, Boolean) -> Unit,   // text, action, handled
    private val onAudioReceived: (ByteArray) -> Unit
) : WebSocketListener() {

    private val client = OkHttpClient.Builder()
        .readTimeout(0, TimeUnit.MILLISECONDS) // Disable timeout for long-lived connection
        .pingInterval(30, TimeUnit.SECONDS)
        .build()
    private val logger = LoggerFactory.getLogger(VoiceWebSocketClient::class.java)
    private val messageFactory = VoiceWebSocketMessageFactory()
    
    private var webSocket: WebSocket? = null
    private var isConnected = false
    
    /** Flag to control audio sending - set by VoiceSession based on current state */
    @Volatile var isSendingAllowed = false
    
    // Current command's correlation ID for tracing
    @Volatile var currentCorrelationId: String? = null
    
    // Auto-reconnect state
    private var reconnectAttempts = 0
    private val maxReconnectAttempts = 5
    private var shouldReconnect = true
    
    fun connect() {
        if (isConnected) return
        
        shouldReconnect = true
        
        val requestBuilder = Request.Builder()
            .url(url)

        val token = TokenManager.getAccessToken()
        if (!token.isNullOrBlank()) {
            requestBuilder.addHeader("Authorization", "Bearer $token")
        } else {
            logger.debug("No access token available for Voice WS - connecting without Authorization header")
        }

        val userId = TokenManager.getUserId()
        if (!userId.isNullOrBlank()) {
            requestBuilder.addHeader("X-User-Id", userId)
        }

        val username = TokenManager.getUsername()
        if (!username.isNullOrBlank()) {
            requestBuilder.addHeader("X-Username", username)
        }

        val role = TokenManager.getUserRole()
        if (!role.isNullOrBlank()) {
            requestBuilder.addHeader("X-User-Roles", role)
        }

        val request = requestBuilder.build()
        
        logger.info("🔌 Connecting to Voice WebSocket: {}", url)
        webSocket = client.newWebSocket(request, this)
    }
    
    fun disconnect() {
        shouldReconnect = false
        webSocket?.close(1000, "Client disconnecting")
        webSocket = null
        isConnected = false
        onStateChange("DISCONNECTED")
    }
    
    private fun scheduleReconnect() {
        if (!shouldReconnect || reconnectAttempts >= maxReconnectAttempts) {
            logger.warn("🔌 Not reconnecting: shouldReconnect={}, attempts={}/{}", 
                shouldReconnect, reconnectAttempts, maxReconnectAttempts)
            if (reconnectAttempts >= maxReconnectAttempts) {
                Platform.runLater {
                    onStateChange("UNAVAILABLE: voice backend not reachable after $maxReconnectAttempts attempts")
                }
            }
            return
        }
        
        reconnectAttempts++
        val delay = minOf(reconnectAttempts * reconnectAttempts * 2, 30) // Exponential: 2, 8, 18, 30, 30
        logger.info("🔌 Scheduling Voice WS reconnect attempt {}/{} in {}s", 
            reconnectAttempts, maxReconnectAttempts, delay)
        
        Platform.runLater { onStateChange("Reconnecting in ${delay}s (attempt $reconnectAttempts/$maxReconnectAttempts)...") }
        
        Thread {
            Thread.sleep(delay * 1000L)
            if (!isConnected && shouldReconnect) {
                logger.info("🔌 Attempting Voice WS reconnect...")
                connect()
            }
        }.start()
    }
    
    /**
     * Start a new voice command session with the given correlationId.
     * The correlationId is generated by VoiceSession and passed here to ensure
     * a single unified ID is used across the entire pipeline.
     * 
     * @param correlationId The unified correlation ID from VoiceSession
     */
    fun startCommand(correlationId: String) {
        currentCorrelationId = correlationId
        
        if (!isConnected) {
            logger.warn("⚠️ Cannot start command - not connected, correlationId={}", correlationId)
            return
        }
        
        val msg = buildJsonObject {
            put("type", "START")
            put("correlationId", correlationId)
        }.toString()
        
        logger.info("🎤 Starting voice command, correlationId={}", correlationId)
        webSocket?.send(msg)
    }
    
    fun sendAudio(data: ByteArray) {
        if (!isConnected) return
        if (!isSendingAllowed) {
            // Skip sending audio when not in LISTENING state (TTS playback, cooldown, etc.)
            return
        }
        logger.debug("📤 Sending audio chunk: {} bytes, correlationId={}", data.size, currentCorrelationId)
        webSocket?.send(data.toByteString())
    }
    
    fun sendConfig(config: Map<String, String>) {
        if (!isConnected || config.isEmpty()) return
        val message = messageFactory.configMessage(config)
        logger.info("🎛️ Sending voice config: {}", config)
        webSocket?.send(message)
    }

    fun endOfSpeech() {
        if (!isConnected) return
        val msg = buildJsonObject {
            put("type", "END")
            put("correlationId", currentCorrelationId ?: "")
        }.toString()
        logger.info("⏹️ Sending end-of-speech marker, correlationId={}", currentCorrelationId)
        webSocket?.send(msg)
    }
    
    /**
     * Request TTS phrase for STT timeout ("Sir, I couldn't hear you").
     * Used when the listen timeout expires without receiving a final transcript.
     */
    fun requestTimeoutPhrase() {
        if (!isConnected) return
        val msg = buildJsonObject {
            put("type", "TIMEOUT")
            put("correlationId", currentCorrelationId ?: "")
        }.toString()
        logger.info("⏰ Requesting timeout phrase, correlationId={}", currentCorrelationId)
        webSocket?.send(msg)
    }
    
    /**
     * Clear current correlation ID after command processing is complete.
     */
    fun clearCorrelationId() {
        logger.debug("Clearing correlationId={}", currentCorrelationId)
        currentCorrelationId = null
    }

    override fun onOpen(webSocket: WebSocket, response: Response) {
        isConnected = true
        reconnectAttempts = 0 // Reset on successful connection
        logger.info("🔌 Voice WS connected: ${response.request.url}")
        Platform.runLater { onStateChange("CONNECTED") }
        sendConfig(mapOf("language" to AppConfig.voiceLanguage))
    }

    override fun onMessage(webSocket: WebSocket, text: String) {
        try {
            val json = Json.parseToJsonElement(text).jsonObject
            val type = json["type"]?.jsonPrimitive?.content
            val msgCorrelationId = json["correlationId"]?.jsonPrimitive?.contentOrNull
            
            Platform.runLater {
                when (type) {
                    "STATE" -> {
                        val state = json["state"]?.jsonPrimitive?.content ?: "UNKNOWN"
                        val sttAvailable = json["sttAvailable"]?.jsonPrimitive?.booleanOrNull
                        onStateChange(state)
                        if (sttAvailable == false) {
                            onStateChange("UNAVAILABLE: STT backend is not configured on the server")
                        }
                    }
                    "TRANSCRIPT_PARTIAL" -> {
                        val transcript = json["text"]?.jsonPrimitive?.content ?: ""
                        logger.debug("📝 Partial transcript: '{}', correlationId={}", transcript, msgCorrelationId)
                        onTranscript(transcript, false, msgCorrelationId)
                    }
                    "TRANSCRIPT_FINAL" -> {
                        val transcript = json["text"]?.jsonPrimitive?.content ?: ""
                        logger.info("📝 Final transcript: '{}', correlationId={}", transcript, msgCorrelationId)
                        // IMPORTANT: Notify about final transcript immediately
                        // so VoiceSession can stop recording ASAP
                        onTranscript(transcript, true, msgCorrelationId)
                    }
                    "RESPONSE" -> {
                        val responseText = json["text"]?.jsonPrimitive?.content ?: ""
                        val action = json["action"]?.jsonPrimitive?.contentOrNull
                        val handled = json["handled"]?.jsonPrimitive?.booleanOrNull ?: false
                        logger.info("📢 Response: '{}', action={}, handled={}, correlationId={}", 
                            responseText, action, handled, msgCorrelationId)
                        if (action == "STT_UNAVAILABLE") {
                            onStateChange("UNAVAILABLE: $responseText")
                        }
                        onResponse(responseText, action, handled)
                    }
                    "ACTION_RESULT" -> {
                        val success = json["success"]?.jsonPrimitive?.booleanOrNull ?: false
                        val message = json["message"]?.jsonPrimitive?.contentOrNull ?: ""
                        logger.info("✅ Action result: success={}, message='{}', correlationId={}", 
                            success, message, msgCorrelationId)
                    }
                }
            }
        } catch (e: Exception) {
            logger.error("Error parsing message: {}", text, e)
        }
    }

    override fun onMessage(webSocket: WebSocket, bytes: okio.ByteString) {
        // Received TTS audio
        val audioData = bytes.toByteArray()
        Platform.runLater { onAudioReceived(audioData) }
    }

    override fun onClosing(webSocket: WebSocket, code: Int, reason: String) {
        logger.warn("⚠️ Voice WS closing: code={}, reason={}", code, reason)
        // Don't set isConnected=false here, wait for onClosed
    }
    
    override fun onClosed(webSocket: WebSocket, code: Int, reason: String) {
        isConnected = false
        logger.warn("🔌 Voice WS closed: code={}, reason={}", code, reason)
        Platform.runLater { onStateChange("DISCONNECTED") }
        
        // Auto-reconnect if not intentional close (1000 = normal close)
        if (code != 1000 && shouldReconnect) {
            scheduleReconnect()
        }
    }

    override fun onFailure(webSocket: WebSocket, t: Throwable, response: Response?) {
        isConnected = false
        logger.error("❌ Voice WS failure: {}, code={}", t.message, response?.code)
        Platform.runLater { onStateChange("ERROR: ${t.message}") }
        
        // Auto-reconnect on failure
        if (shouldReconnect) {
            scheduleReconnect()
        }
    }
}
