apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod-release-internal-tls-orchestrator-api-gateway

patches:
  - path: voice-gateway.patch.yaml
  - path: api-gateway-ingress-allow.patch.yaml
    target:
      kind: NetworkPolicy
      name: api-gateway-ingress-allow
  - path: voice-gateway-egress-api-gateway.patch.yaml
    target:
      kind: NetworkPolicy
      name: voice-gateway-egress-orchestrator
