#!/usr/bin/env bash

# =============================================================================
# Jarvis 2.0 - Apply Local Secrets to Kubernetes
# =============================================================================
# Reads secrets from ~/.jarvis/secrets/secrets.env (or ./secrets/secrets.env)
# and creates/updates Kubernetes secret jarvis-secrets in namespace jarvis
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
GRAY='\033[0;90m'
NC='\033[0m'

NAMESPACE="jarvis"
SECRET_NAME="jarvis-secrets"

# Parse arguments
SECRETS_DIR=""
INIT=false
NO_APPLY=false
for arg in "$@"; do
    case "$arg" in
        --dir=*|--secrets-dir=*)
            SECRETS_DIR="${arg#*=}"
            ;;
        --init|--auto-init)
            INIT=true
            ;;
        --no-apply)
            NO_APPLY=true
            ;;
        --help|-h)
            echo "Usage: $0 [--dir=<path>]"
            echo ""
            echo "Options:"
            echo "  --dir=<path>     Use custom secrets directory"
            echo "  --init           Create secrets file if missing"
            echo "  --no-apply       Only create/validate secrets file (skip kubectl)"
            echo "  --help, -h       Show this help"
            echo ""
            echo "Default: Uses ~/.jarvis/secrets/secrets.env"
            exit 0
            ;;
    esac
done

# Determine secrets file location
if [[ -n "$SECRETS_DIR" ]]; then
    SECRETS_FILE="${SECRETS_DIR}/secrets.env"
else
    SECRETS_FILE="${HOME}/.jarvis/secrets/secrets.env"
fi

echo "=========================================="
echo "Jarvis 2.0 - Apply Secrets to Kubernetes"
echo "=========================================="
echo ""
echo "Secrets file: ${SECRETS_FILE}"
echo "Namespace: ${NAMESPACE}"
echo "Secret name: ${SECRET_NAME}"
echo ""

generate_secrets_file() {
    if ! command -v openssl >/dev/null 2>&1; then
        echo -e "${RED}❌ openssl not found; cannot auto-generate secrets${NC}"
        exit 1
    fi

    mkdir -p "$(dirname "${SECRETS_FILE}")"
    umask 077

    local db_password rabbit_password rabbit_cookie jwt_secret enc_key
    db_password="$(openssl rand -base64 32 | tr -d '\n')"
    rabbit_password="$(openssl rand -base64 32 | tr -d '\n')"
    rabbit_cookie="$(openssl rand -base64 32 | tr -d '\n')"
    jwt_secret="$(openssl rand -base64 32 | tr -d '\n')"
    enc_key="$(openssl rand -base64 32 | tr -d '\n')"

    cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by jarvis-secrets-apply.sh
POSTGRES_USER=jarvis
POSTGRES_PASSWORD=${db_password}
SPRING_DATASOURCE_USERNAME=jarvis
SPRING_DATASOURCE_PASSWORD=${db_password}
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.jarvis.svc.cluster.local:5432/jarvis

RABBITMQ_DEFAULT_USER=jarvis
RABBITMQ_DEFAULT_PASS=${rabbit_password}
RABBITMQ_ERLANG_COOKIE=${rabbit_cookie}
SPRING_RABBITMQ_USERNAME=jarvis
SPRING_RABBITMQ_PASSWORD=${rabbit_password}

JWT_SECRET=${jwt_secret}
ENCRYPTION_KEY=${enc_key}
EOF

    chmod 600 "${SECRETS_FILE}"
    echo -e "${GREEN}✅ Secrets file created: ${SECRETS_FILE}${NC}"
}

# Check if secrets file exists
if [[ ! -f "$SECRETS_FILE" ]]; then
    if [[ "$INIT" == "true" ]]; then
        generate_secrets_file
        if [[ "$NO_APPLY" == "true" ]]; then
            exit 0
        fi
    else
        echo -e "${RED}❌ Secrets file not found: ${SECRETS_FILE}${NC}"
        echo ""
        echo -e "${YELLOW}💡 To create secrets:${NC}"
        echo "  1. Copy template:"
        echo "     cp ${REPO_ROOT}/secrets/secrets.example.env ${SECRETS_FILE}"
        echo ""
        echo "  2. Edit with your values:"
        echo "     nano ${SECRETS_FILE}"
        echo ""
        echo "  3. Set permissions:"
        echo "     chmod 600 ${SECRETS_FILE}"
        echo ""
        echo "  4. Run this script again:"
        echo "     $0"
        echo ""
        echo -e "${GRAY}See docs/security/SECRETS_POLICY.md for details.${NC}"
        exit 1
    fi
fi

# Check file permissions (should be 600)
FILE_PERMS=$(stat -c "%a" "$SECRETS_FILE" 2>/dev/null || stat -f "%OLp" "$SECRETS_FILE" 2>/dev/null || echo "unknown")
if [[ "$FILE_PERMS" != "600" ]] && [[ "$FILE_PERMS" != "unknown" ]]; then
    echo -e "${YELLOW}⚠️  Warning: Secrets file permissions are $FILE_PERMS (recommended: 600)${NC}"
    echo -e "${GRAY}   Run: chmod 600 ${SECRETS_FILE}${NC}"
    echo ""
fi

# Skip kubectl if requested
if [[ "$NO_APPLY" == "true" ]]; then
    echo -e "${YELLOW}⚠️  --no-apply set; skipping kubectl apply${NC}"
    exit 0
fi

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo -e "${RED}❌ kubectl not found${NC}"
    echo "   Please install kubectl first"
    exit 1
fi

# Check if namespace exists
if ! kubectl get namespace "$NAMESPACE" >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Namespace '$NAMESPACE' does not exist, creating...${NC}"
    kubectl create namespace "$NAMESPACE"
    echo -e "${GREEN}✅ Namespace created${NC}"
fi

# Parse secrets file (skip comments and empty lines)
echo "Reading secrets from file..."
declare -A SECRET_VALUES
REQUIRED_KEYS=(
    "POSTGRES_USER"
    "POSTGRES_PASSWORD"
    "SPRING_DATASOURCE_USERNAME"
    "SPRING_DATASOURCE_PASSWORD"
    "SPRING_DATASOURCE_URL"
    "RABBITMQ_DEFAULT_USER"
    "RABBITMQ_DEFAULT_PASS"
    "RABBITMQ_ERLANG_COOKIE"
    "SPRING_RABBITMQ_USERNAME"
    "SPRING_RABBITMQ_PASSWORD"
    "JWT_SECRET"
)

while IFS='=' read -r key value || [[ -n "$key" ]]; do
    # Skip comments and empty lines
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${key// }" ]] && continue
    
    # Remove leading/trailing whitespace
    key=$(echo "$key" | xargs)
    value=$(echo "$value" | xargs)
    
    # Remove quotes if present
    value="${value#\"}"
    value="${value%\"}"
    value="${value#\'}"
    value="${value%\'}"
    
    if [[ -n "$key" ]] && [[ -n "$value" ]]; then
        SECRET_VALUES["$key"]="$value"
    fi
done < "$SECRETS_FILE"

# Check for required keys
echo "Validating required keys..."
MISSING_KEYS=()
for key in "${REQUIRED_KEYS[@]}"; do
    if [[ -z "${SECRET_VALUES[$key]:-}" ]]; then
        MISSING_KEYS+=("$key")
    fi
done

if [[ ${#MISSING_KEYS[@]} -gt 0 ]]; then
    echo -e "${RED}❌ Missing required keys:${NC}"
    for key in "${MISSING_KEYS[@]}"; do
        echo "   - $key"
    done
    echo ""
    echo -e "${YELLOW}💡 Add these keys to ${SECRETS_FILE}${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All required keys present${NC}"
echo ""

# Build kubectl command
echo "Applying secrets to Kubernetes..."
KUBECTL_ARGS=()

# Add all secret values (never print values, only keys)
for key in "${!SECRET_VALUES[@]}"; do
    value="${SECRET_VALUES[$key]}"
    KUBECTL_ARGS+=("--from-literal=${key}=${value}")
    echo -e "  ${GRAY}✓${NC} ${key} (value hidden)"
done

# Create or replace secret (idempotent)
if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
    echo ""
    echo -e "${CYAN}Secret '$SECRET_NAME' already exists, updating...${NC}"
    kubectl delete secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1 || true
fi

kubectl create secret generic "$SECRET_NAME" \
    "${KUBECTL_ARGS[@]}" \
    -n "$NAMESPACE" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
    echo ""
    echo -e "${GREEN}✅ Secret '$SECRET_NAME' applied successfully${NC}"
    echo ""
    echo "Verifying secret..."
    if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
        SECRET_KEYS=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data}' | grep -o '"[^"]*":' | tr -d '":' | sort)
        echo -e "${GREEN}✅ Secret verified (keys: $(echo $SECRET_KEYS | tr '\n' ' '))${NC}"
    else
        echo -e "${RED}❌ Secret verification failed${NC}"
        exit 1
    fi
else
    echo -e "${RED}❌ Failed to apply secret${NC}"
    exit 1
fi

echo ""
echo "=========================================="
echo "Secrets applied successfully!"
echo "=========================================="
echo ""
echo -e "${GRAY}Note: Secret values are never printed in logs for security.${NC}"
