#!/usr/bin/env bash

# =============================================================================
# Jarvis 2.0 - Apply Local Secrets to Kubernetes
# =============================================================================
# Reads secrets from ~/.jarvis/secrets/secrets.env (or ./secrets/secrets.env)
# and creates/updates Kubernetes secret jarvis-secrets in namespace jarvis-prod
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/lib/k8s-common.sh"

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
GRAY='\033[0;90m'
NC='\033[0m'

NAMESPACE="${JARVIS_NAMESPACE:-jarvis-prod}"
SECRET_NAME="jarvis-secrets"
GRAFANA_ADMIN_USER_KEY="GRAFANA_ADMIN_USER"
GRAFANA_ADMIN_PASSWORD_KEY="GRAFANA_ADMIN_PASSWORD"

# Parse arguments
SECRETS_DIR=""
INIT=false
NO_APPLY=false
for arg in "$@"; do
    case "$arg" in
        --dir=*|--secrets-dir=*)
            SECRETS_DIR="${arg#*=}"
            ;;
        --init|--auto-init)
            INIT=true
            ;;
        --no-apply)
            NO_APPLY=true
            ;;
        --help|-h)
            echo "Usage: $0 [--dir=<path>]"
            echo ""
            echo "Options:"
            echo "  --dir=<path>     Use custom secrets directory"
            echo "  --init           Create secrets file if missing"
            echo "  --no-apply       Only create/validate secrets file (skip kubectl)"
            echo "  --help, -h       Show this help"
            echo ""
            echo "Default: Uses ~/.jarvis/secrets/secrets.env"
            exit 0
            ;;
    esac
done

# Determine secrets file location
if [[ -n "$SECRETS_DIR" ]]; then
    SECRETS_FILE="${SECRETS_DIR}/secrets.env"
else
    SECRETS_FILE="${HOME}/.jarvis/secrets/secrets.env"
fi

echo "=========================================="
echo "Jarvis 2.0 - Apply Secrets to Kubernetes"
echo "=========================================="
echo ""
echo "Secrets file: ${SECRETS_FILE}"
echo "Namespace: ${NAMESPACE}"
echo "Secret name: ${SECRET_NAME}"
echo ""

generate_secrets_file() {
    if ! command -v openssl >/dev/null 2>&1; then
        echo -e "${RED}❌ openssl not found; cannot auto-generate secrets${NC}"
        exit 1
    fi

    mkdir -p "$(dirname "${SECRETS_FILE}")"
    umask 077

    local db_password rabbit_password rabbit_cookie mqtt_password jwt_secret service_jwt_secret enc_key grafana_password
    db_password="$(openssl rand -base64 32 | tr -d '\n')"
    rabbit_password="$(openssl rand -base64 32 | tr -d '\n')"
    rabbit_cookie="$(openssl rand -base64 32 | tr -d '\n')"
    mqtt_password="$(openssl rand -base64 32 | tr -d '\n')"
    jwt_secret="$(openssl rand -base64 32 | tr -d '\n')"
    service_jwt_secret="$(openssl rand -base64 32 | tr -d '\n')"
    enc_key="$(openssl rand -base64 32 | tr -d '\n')"
    grafana_password="$(openssl rand -base64 32 | tr -d '\n')"

    cat > "${SECRETS_FILE}" <<EOF
# Auto-generated by jarvis-secrets-apply.sh
POSTGRES_USER=jarvis
POSTGRES_PASSWORD=${db_password}
SPRING_DATASOURCE_USERNAME=jarvis
SPRING_DATASOURCE_PASSWORD=${db_password}
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres.jarvis-prod.svc.cluster.local:5432/jarvis

RABBITMQ_DEFAULT_USER=jarvis
RABBITMQ_DEFAULT_PASS=${rabbit_password}
RABBITMQ_ERLANG_COOKIE=${rabbit_cookie}
SPRING_RABBITMQ_USERNAME=jarvis
SPRING_RABBITMQ_PASSWORD=${rabbit_password}
MQTT_USERNAME=jarvis_mqtt
MQTT_PASSWORD=${mqtt_password}

JWT_SECRET=${jwt_secret}
SERVICE_JWT_SECRET=${service_jwt_secret}
ENCRYPTION_KEY=${enc_key}

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${grafana_password}
EOF

    chmod 600 "${SECRETS_FILE}"
    echo -e "${GREEN}✅ Secrets file created: ${SECRETS_FILE}${NC}"
}

# Check if secrets file exists
if [[ ! -f "$SECRETS_FILE" ]]; then
    if [[ "$INIT" == "true" ]]; then
        generate_secrets_file
        if [[ "$NO_APPLY" == "true" ]]; then
            exit 0
        fi
    else
        echo -e "${RED}❌ Secrets file not found: ${SECRETS_FILE}${NC}"
        echo ""
        echo -e "${YELLOW}💡 To create secrets:${NC}"
        echo "  1. Copy template:"
        echo "     cp ${REPO_ROOT}/secrets/secrets.example.env ${SECRETS_FILE}"
        echo ""
        echo "  2. Edit with your values:"
        echo "     nano ${SECRETS_FILE}"
        echo ""
        echo "  3. Set permissions:"
        echo "     chmod 600 ${SECRETS_FILE}"
        echo ""
        echo "  4. Run this script again:"
        echo "     $0"
        echo ""
        echo -e "${GRAY}See README.md for the current canonical documentation.${NC}"
        exit 1
    fi
fi

# Check file permissions (should be 600)
FILE_PERMS=$(stat -c "%a" "$SECRETS_FILE" 2>/dev/null || stat -f "%OLp" "$SECRETS_FILE" 2>/dev/null || echo "unknown")
if [[ "$FILE_PERMS" != "600" ]] && [[ "$FILE_PERMS" != "unknown" ]]; then
    echo -e "${YELLOW}⚠️  Warning: Secrets file permissions are $FILE_PERMS (recommended: 600)${NC}"
    echo -e "${GRAY}   Run: chmod 600 ${SECRETS_FILE}${NC}"
    echo ""
fi

# Skip kubectl if requested
if [[ "$NO_APPLY" == "true" ]]; then
    echo -e "${YELLOW}⚠️  --no-apply set; skipping kubectl apply${NC}"
    exit 0
fi

# Check if kubectl or microk8s is available
if ! jarvis_require_kubectl >/dev/null 2>&1; then
    echo -e "${RED}❌ Neither kubectl nor microk8s is available${NC}"
    exit 1
fi

echo "Using Kubernetes CLI: $(jarvis_kubectl_description)"

# Check if namespace exists
if ! kubectl get namespace "$NAMESPACE" >/dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Namespace '$NAMESPACE' does not exist, creating...${NC}"
    kubectl create namespace "$NAMESPACE"
    echo -e "${GREEN}✅ Namespace created${NC}"
fi

# Parse secrets file (skip comments and empty lines)
echo "Reading secrets from file..."
declare -A SECRET_VALUES
REQUIRED_KEYS=(
    "POSTGRES_USER"
    "POSTGRES_PASSWORD"
    "SPRING_DATASOURCE_USERNAME"
    "SPRING_DATASOURCE_PASSWORD"
    "SPRING_DATASOURCE_URL"
    "RABBITMQ_DEFAULT_USER"
    "RABBITMQ_DEFAULT_PASS"
    "RABBITMQ_ERLANG_COOKIE"
    "SPRING_RABBITMQ_USERNAME"
    "SPRING_RABBITMQ_PASSWORD"
    "MQTT_USERNAME"
    "MQTT_PASSWORD"
    "JWT_SECRET"
    "SERVICE_JWT_SECRET"
)

while IFS= read -r line || [[ -n "$line" ]]; do
    # Skip comments and empty lines while preserving '=' inside values.
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line//[[:space:]]/}" ]] && continue
    [[ "$line" != *"="* ]] && continue

    key="${line%%=*}"
    value="${line#*=}"

    # Remove leading/trailing whitespace without altering base64 padding.
    key="$(printf '%s' "$key" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    value="$(printf '%s' "$value" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

    # Remove quotes if present
    value="${value#\"}"
    value="${value%\"}"
    value="${value#\'}"
    value="${value%\'}"

    if [[ -n "$key" ]] && [[ -n "$value" ]]; then
        SECRET_VALUES["$key"]="$value"
    fi
done < "$SECRETS_FILE"

EXPECTED_SPRING_DATASOURCE_URL="jdbc:postgresql://postgres.${NAMESPACE}.svc.cluster.local:5432/jarvis"
if [[ "${SECRET_VALUES[SPRING_DATASOURCE_URL]:-}" != "${EXPECTED_SPRING_DATASOURCE_URL}" ]]; then
    SECRET_VALUES["SPRING_DATASOURCE_URL"]="${EXPECTED_SPRING_DATASOURCE_URL}"
    echo -e "${CYAN}Normalizing SPRING_DATASOURCE_URL for namespace ${NAMESPACE}${NC}"
fi

ensure_grafana_admin_secrets() {
    local updated="false"
    local user_missing="false"
    local password_missing="false"

    if [[ -z "${SECRET_VALUES[$GRAFANA_ADMIN_USER_KEY]:-}" ]]; then
        SECRET_VALUES["$GRAFANA_ADMIN_USER_KEY"]="admin"
        updated="true"
        user_missing="true"
    fi

    if [[ -z "${SECRET_VALUES[$GRAFANA_ADMIN_PASSWORD_KEY]:-}" ]]; then
        if ! command -v openssl >/dev/null 2>&1; then
            echo -e "${RED}❌ openssl not found; cannot generate ${GRAFANA_ADMIN_PASSWORD_KEY}${NC}"
            exit 1
        fi
        SECRET_VALUES["$GRAFANA_ADMIN_PASSWORD_KEY"]="$(openssl rand -base64 32 | tr -d '\n')"
        updated="true"
        password_missing="true"
    fi

    if [[ "${updated}" != "true" ]]; then
        return 0
    fi

    chmod 600 "${SECRETS_FILE}" >/dev/null 2>&1 || true
    {
        echo ""
        echo "# Grafana admin credentials"
        if [[ "${user_missing}" == "true" ]]; then
            echo "${GRAFANA_ADMIN_USER_KEY}=${SECRET_VALUES[$GRAFANA_ADMIN_USER_KEY]}"
        fi
        if [[ "${password_missing}" == "true" ]]; then
            echo "${GRAFANA_ADMIN_PASSWORD_KEY}=${SECRET_VALUES[$GRAFANA_ADMIN_PASSWORD_KEY]}"
        fi
    } >> "${SECRETS_FILE}"

    echo -e "${CYAN}Backfilled ${GRAFANA_ADMIN_USER_KEY} / ${GRAFANA_ADMIN_PASSWORD_KEY} into ${SECRETS_FILE}${NC}"
}

ensure_grafana_admin_secrets

# Check for required keys
echo "Validating required keys..."
MISSING_KEYS=()
for key in "${REQUIRED_KEYS[@]}"; do
    if [[ -z "${SECRET_VALUES[$key]:-}" ]]; then
        MISSING_KEYS+=("$key")
    fi
done

if [[ ${#MISSING_KEYS[@]} -gt 0 ]]; then
    echo -e "${RED}❌ Missing required keys:${NC}"
    for key in "${MISSING_KEYS[@]}"; do
        echo "   - $key"
    done
    echo ""
    echo -e "${YELLOW}💡 Add these keys to ${SECRETS_FILE}${NC}"
    exit 1
fi

echo -e "${GREEN}✅ All required keys present${NC}"
echo ""

echo "Applying secrets to Kubernetes..."
KUBECTL_ARGS=()

# Add all secret values (never print values, only keys)
for key in "${!SECRET_VALUES[@]}"; do
    value="${SECRET_VALUES[$key]}"
    KUBECTL_ARGS+=("--from-literal=${key}=${value}")
    echo -e "  ${GRAY}✓${NC} ${key} (value hidden)"
done

# Create or update secret idempotently
if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
    echo ""
    echo -e "${CYAN}Secret '$SECRET_NAME' already exists, updating in place...${NC}"
fi

kubectl create secret generic "$SECRET_NAME" \
    "${KUBECTL_ARGS[@]}" \
    -n "$NAMESPACE" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null 2>&1

if [[ $? -eq 0 ]]; then
    echo ""
    echo -e "${GREEN}✅ Secret '$SECRET_NAME' applied successfully${NC}"
    echo ""
    echo "Verifying secret..."
    if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" >/dev/null 2>&1; then
        SECRET_KEYS=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data}' | grep -o '"[^"]*":' | tr -d '":' | sort)
        echo -e "${GREEN}✅ Secret verified (keys: $(echo $SECRET_KEYS | tr '\n' ' '))${NC}"
    else
        echo -e "${RED}❌ Secret verification failed${NC}"
        exit 1
    fi

    echo ""
    echo "Restarting workloads that consume rotated secrets..."
    for deployment in mosquitto smart-home-service; do
        if kubectl -n "$NAMESPACE" get deployment "$deployment" >/dev/null 2>&1; then
            kubectl -n "$NAMESPACE" rollout restart deployment/"$deployment" >/dev/null 2>&1 || true
            echo -e "  ${GRAY}↻${NC} restarted deployment/$deployment"
        fi
    done
else
    echo -e "${RED}❌ Failed to apply secret${NC}"
    exit 1
fi

echo ""
echo "=========================================="
echo "Secrets applied successfully!"
echo "=========================================="
echo ""
echo -e "${GRAY}Note: Secret values are never printed in logs for security.${NC}"
