package org.jarvis.swarm.executor.role;

import org.jarvis.swarm.executor.ExecutionContext;
import org.jarvis.swarm.executor.RoleExecutor;
import org.jarvis.swarm.executor.RoleResult;
import org.jarvis.swarm.role.AgentRole;
import org.jarvis.swarm.sandbox.SandboxManager;
import org.springframework.stereotype.Component;

import java.nio.file.Path;
import java.util.List;

/**
 * DOCS: generates or updates documentation from the goal and writes it into its sandbox.
 * No shell required. dryRun returns the proposed document outline without writing.
 */
@Component
public class DocsAgentExecutor implements RoleExecutor {

    private final SandboxManager sandbox;

    public DocsAgentExecutor(SandboxManager sandbox) {
        this.sandbox = sandbox;
    }

    @Override
    public AgentRole role() {
        return AgentRole.DOCS;
    }

    @Override
    public RoleResult execute(ExecutionContext ctx) {
        ctx.checkpoint();
        String goal = ctx.task().goal();
        String doc = render(goal);
        List<String> proposed = List.of("create docs/README.md", "sections: Overview, Usage, Notes");

        if (ctx.dryRun() || ctx.sandbox() == null) {
            return RoleResult.success("DOCS outline (dry-run) for: " + goal,
                    doc, List.of(), proposed, List.of(), List.of("Review and place docs in the repo"));
        }
        Path file = sandbox.writeFile(ctx.sandbox(), "docs/README.md", doc);
        return RoleResult.success("DOCS generated documentation in sandbox",
                doc, List.of(file.toString()), proposed, List.of(), List.of());
    }

    private String render(String goal) {
        return "# Documentation\n\n## Overview\n" + goal + "\n\n## Usage\n"
                + "Describe how to use the feature implementing: " + goal + "\n\n## Notes\n"
                + "- Generated by the DOCS agent in an isolated sandbox.\n";
    }
}
