package org.jarvis.common;

/**
 * Canonical HTTP header names used across Jarvis microservices.
 *
 * <h3>Request Correlation Semantics</h3>
 * <ul>
 *   <li><b>{@link #CORRELATION_ID}</b> — application-level request correlation.
 *       Identifies a single user-initiated action end-to-end: from voice-gateway /
 *       desktop-client through orchestrator to llm-service and memory-service.
 *       Set by the originating client (voice-gateway, desktop, curl) and
 *       propagated by every Feign / RestClient hop. If absent, services
 *       generate a UUID fallback.</li>
 *   <li><b>{@link #TRACE_ID}</b> — infrastructure-level distributed trace.
 *       Generated by {@code TraceFilter} at the API gateway edge and placed
 *       into MDC for structured logging. Separate from correlation ID because
 *       a single user action may produce multiple independent traces (e.g.
 *       gateway → orchestrator → llm-service each start their own span).</li>
 *   <li><b>Body-level {@code correlationId}</b> — retained in JSON request /
 *       response bodies (voice WebSocket messages, orchestrator execute body)
 *       for backward compatibility with existing clients. These mirror
 *       the header value; the header is the canonical source of truth.</li>
 * </ul>
 *
 * <h3>Model Profile</h3>
 * <ul>
 *   <li><b>{@link #MODEL_PROFILE}</b> — channel-aware inference profile
 *       (e.g. {@code voice-fast}, {@code desktop-general}, {@code orchestration}).
 *       Determines max_tokens, temperature, timeout, and admission priority.</li>
 * </ul>
 */
public final class JarvisHttpHeaders {

    private JarvisHttpHeaders() {
    }

    /** Application-level request correlation (set by originating client). */
    public static final String CORRELATION_ID = "X-Correlation-ID";

    /** Infrastructure-level distributed trace (set by gateway TraceFilter). */
    public static final String TRACE_ID = "X-Trace-Id";

    /** Channel-aware model profile for inference routing. */
    public static final String MODEL_PROFILE = "X-Model-Profile";

    /** Authenticated user identity propagated by the gateway. */
    public static final String USER_ID = "X-User-Id";

    /** MDC key used by TracePropagationFilter for structured logging. */
    public static final String TRACE_ID_MDC_KEY = "traceId";
}
