apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: jarvis
spec:
  template:
    metadata:
      annotations:
        jarvis.io/internal-tls-slice-api-gateway-security-service: api-gateway-security-service-v1
    spec:
      containers:
        - name: api-gateway
          env:
            - name: SECURITY_URL
              value: https://security-service.jarvis.svc.cluster.local:8088
