apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../prod-release-internal-tls-ingress-api-gateway

patches:
  - path: api-gateway.patch.yaml
  - path: security-service.patch.yaml
