apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jarvis-prod

resources:
  - ../prod-release-internal-tls-voice-gateway-orchestrator

patches:
  - path: analytics-service.patch.yaml
